### PR TITLE
Bump bytestring dependency upper bound to < 0.12

### PR DESCRIPTION
**Pull request by SamuelSchlesinger**
Found myself needing this bumped to build a project.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Ping @hvr

**Comment by Bodigrim** [comment]
CC @phadej @chessai
This is holding many packages downstream. Is there anything I can help with to get it merged and revised on Hackage?

**Comment by chessai** [comment]
> CC @phadej @chessai
> This is holding many packages downstream. Is there anything I can help with to get it merged and revised on Hackage?

Reached out to gershom for hackage rights

**Comment by phadej** [comment]
What? Is this package takeover? There is clear procedure for that. You can also ask Hackage Trustees to make a revision.

I'm neither the maintainer of `hashable` nor Hackage Trustee, so I cannot help here.

... but, what the fuck?

**Comment by chessai** [comment]
Oops, my bad. Thought this was under haskell/. I will ask for gershom to
not go through with my request.

**Comment by chessai** [comment]
@gbaz could you make a hackage revision for this, until it's merged?

**Comment by phadej** [comment]
Also since when packages under `haskell` GitHub organization are under any other policy?

Does this mean that CLC oversees changes in e.g. `base16-bytestring` and `base64-bytestring` now too? ping @emilypi

**Comment by chessai** [comment]
> Also since when packages under `haskell` GitHub organization are under any other policy, then what the individual packages may have?
> 
> Does this mean that CLC oversees changes in e.g. `base16-bytestring` and `base64-bytestring` now too? ping @emilypi

No, CLC does not. Formally, if this were under haskell/, CLC would be overstepping bounds to help maintain. But there are recent cases of non-CLC-owned packages (such as with bytestring and text) where CLC has stepped in to stop the stalling of packages due to lack of maintenance, and weighted importance of those packages. But, because this is not within haskell/ org, I would definitely leave this to maintainers (and/or hackage trustees for bumping version bounds).

**Comment by gbaz** [comment]
@chessai the right way to get the bound changed is to open an issue at https://github.com/haskell-infra/hackage-trustees/issues

**Comment by chessai** [comment]
> @chessai the right way to get the bound changed is to open an issue at https://github.com/haskell-infra/hackage-trustees/issues

request to make the revision opened: https://github.com/haskell-infra/hackage-trustees/issues/287

**Comment by emilypi** [comment]
@phadej no, the CLC does not maintain the base encoding libraries. They  happen to be under the haskell github umbrella because it was a historical dumping ground for unwanted packages (namely - bos' and a few others). I really think we need to clear up policy on this, because we shouldn't be identifying "core" with "critical to the Haskell ecosystem". "Core" only means GHC boot libraries and a few peripherals, NOT general "everyone uses these so now the CLC has eminent domain".

**Comment by chessai** [comment]
> @phadej no, the CLC does not maintain the base encoding libraries. They happen to be under the haskell github umbrella because it was a historical dumping ground for unwanted packages (namely - bos' and a few others). I really think we need to clear up policy on this, because we shouldn't be identifying "core" with "critical to the Haskell ecosystem". "Core" only means GHC boot libraries and a few peripherals, NOT general "everyone uses these so now the CLC has eminent domain".

I agree with this. It was overstepping bounds to ask for personal maintainership rights. Although I only wanted to bump version bounds, this should always be for the maintainer/trustees to do. I wasn't really thinking about it when I asked, and I apologise. Didn't mean to seem like I was initiating a hostile package takeover.

And the thing I said about bytestring/text - these are boot libraries, _and_ have critical mass, so it seemed natural/not harmful to have CLC put effort toward them. So, to clarify about earlier comments, I wouldn't do this for any library under haskell/.

**Comment by phadej** [comment]
I'll look around at issues and will make a release ASAP. Thank you for your patience.

**Pull request merged**
