### PR TITLE
hashable with different hashers

### PR DESCRIPTION
**Pull request by oberblastmeister**
The code is messy but I wanted to get a review to see if this is okay.

### CODE REVIEW

**Comment by phadej** [comment]
Why this change to begin with? The hashable interface is meant primarily for `unordered-containers`, how they (or rather, their user) would select different hasher?

My first reaction is: :-1:

If someone wants to use different hash, they could use a `newtype`. That is not perfect, as hash state is limited to `Int` (i.e. 64bits on 64bit systems), but this change doesn't improve that fact.

**Comment by oberblastmeister** [comment]
> Why this change to begin with? The hashable interface is meant primarily for unordered-containers

I understand this but it would be nice if we would could have one class for general hashing for use in data structures. The default hasher is terrible and it makes implementing other datastructures such as mutable hashmaps harder. Writing a whole new class just to implement a new algorithm seems not modular. Also, having the hasher fixed makes experimenting with other hashing algorithms much harder. With this change it is as easy as setting the type.

> How they (or rather, their user) would select different hasher?

`HashMap` could have a type parameter for the hash, like `HashMapWith h k v`. Then the library can export a hashmap with a default hasher such as `type HashMap = HashMapWith FnvHasher`. If the user wants to use a different hasher, they can just do `type MyHashMap = HashMapWith SipHasher` and configure the creation for the hashmap. 

> If someone wants to use different hash, they could use a newtype. That is not perfect, as hash state is limited to Int (i.e. 64bits on 64bit systems), but this change doesn't improve that fact.

I don't understand what you mean here.

**Comment by phadej** [comment]
> HashMap could have a type parameter for the hash, like HashMapWith h k v. 

I don't see that hchange going through. Too intrusive. You should discuss that first with @treeown and @sjakobi

> The default hasher is terrible 

Is it? 

> and it makes implementing other datastructures such as mutable hashmaps harder. 

How?

> Writing a whole new class just to implement a new algorithm seems not modular.

Is there a usecase for having different hashing algorithms in use at the same time? Probably, but how common that would be?

If not, than using a flag would be enough to swap the implementation. (If we make "salt" an opaque type, then we can use about any streaming hashing function, that would be a breaking change, but will mostly affect datastructures implementors, not the instances).

The `hashable` implementation is already setup so swapping primitives is relatively straightforward.

---

This kind of intrusive changes have to be discussed first. The sketch of implementation is welcome, but the patch has too much of unrelated changes (commenting out stuff), so seeing the essentials is pretty much impossible.

**Comment by oberblastmeister** [comment]
For example, hashing integers is just `id`. One way that implementing mutable hashmaps is much harder is that since the hash function is not of good quality, power of two arrays can't be used.

> Is there a usecase for having different hashing algorithms in use at the same time? Probably, but how common that would be

Yes, when implementing other data structures. An HAMT probably doesn't care so much about the hash function, but other data structures do.

> but the patch has too much of unrelated changes (commenting out stuff), so seeing the essentials is pretty much impossible.

I comment out stuff because I just want to implement the core, instead of other stuff that can be implemented later and whose design might not be fleshed out yet. What essentials are "pretty much impossible" to see?

**Comment by oberblastmeister** [comment]
This is definitely a bad idea. As you said the library is meant for unordered-containers. Also adding a separate hasher type with a type class will probably mess with specialization and performance.

**Pull request closed without merging**
