### PR TITLE
GHC 9 compatibility fixes

### PR DESCRIPTION
**Pull request by utdemir**
* Use 'Data.Kind.Type' instead of '*'. Using '*' in that position requires `StarIsType` language extension in GHC 9.
* Import `unsafeCoerce#` from `GHC.Exts`  (https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#base-415)
* Relax some upper bounds.

GHC 9 also comes with `ghc-bignum` library which should be preferred over `integer-gmp`. However since it also provides a compatibility shim for `integer-gmp`, so this PR doesn't change that. It would be good to address https://github.com/tibbe/hashable/issues/188 at one point.

I tried to make it backwards-compatible, however; I only tested this PR on GHC HEAD, so I'm hoping for CI to test the older versions.

### CODE REVIEW

**Comment by hvr** [comment]
Thanks!

I'll revisit this PR once the new major GHC 9.0 release enters its final candidate release phase.

**Comment by phadej** [comment]
See #188.

This is "lazy" approach, just bumping `integer-gmp` upper bound...

**Comment by vdukhovni** [comment]
> Thanks! I'll revisit this PR once the new major GHC 9.0 release enters its final candidate release phase.

Cool. GHC 9.0.1-rc1 is now out, so perhaps this is the right time to merge this PR?

**Comment by vmchale** [comment]
GHC 9 is out

**Comment by phadej** [comment]
I'll take a look shortly.

I'll look around at other issues as well and will make a release ASAP. Thank you for your patience.

**Comment by phadej** [comment]
I made few things differently in #195. Thanks for the base work anyway!

**Pull request closed without merging**
